[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib", "../../node_modules"]
solc = "0.8.33"

remappings = [
    "@openzeppelin/=../../node_modules/@openzeppelin/",
    "@account-abstraction/=../../node_modules/@account-abstraction/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
lisk = "${LISK_RPC_URL}"
liskTestnet = "${LISK_TESTNET_RPC_URL}"

[etherscan]
lisk = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 256
